dist: trusty
sudo: required
language: java
jdk:
- oraclejdk8
git:
  depth: 3
cache:
  directories:
  - "$HOME/.m2"
services:
- postgresql
before_script:
- psql -c 'create database frameworkeventstore;' -U postgres
- psql -c 'create database frameworkviewstore;' -U postgres
- psql -c 'create database frameworkfilestore;' -U postgres
- psql -c 'create database frameworksystem;' -U postgres
- psql -c 'create database fileservice;' -U postgres
- psql -c "CREATE USER framework WITH PASSWORD 'framework';" -U postgres
- psql -c "CREATE USER fileservice WITH PASSWORD 'fileservice';" -U postgres
addons:
  postgresql: '9.5'
  sonarcloud:
    organization: cjscommonplatform
    token:
      secure: FAGcFnJBPKyUQLCNA1ZjAQ0eLUZ+HQIDtJh10o9aML8bO+3GE8z8B+pIvAVYwepekXG1YfMvBT3+CmLiLVLO1G+oiI8Ov3tZnIUxWAjGmbyElcXp/FYlc/gemIx9yteZWd6Qi4KXpTARSJuFvSlHU1KoOduNSOPAzi1h4rVIEv27XlmKft3y/X5xWPFLTFnTMD8GP+NSF1JwiHzlbpiKFFgd2iIt5zufsQgdQOLiU3CdxGbKeejbUH7uau8X0xvVFTCa3cnv7YeWakSjSV2fO1WQMONRkr4zZ2vhI1GIREMfiiBhJYqAAs/mErJ7p6BVno2pIr4Si9Vml/xbPPuY6xWYzAd1KG/NdMzFgCNIwRW0MSPHaK5R9DrNqsagJqaa3TGGsFkOK9cQgaPz5BASPCryJG2oBHcwHyexLo5gR3KPLK5g+kedFn4F7olkeiDYtsDeVi1xtiGqUviG/PQR3VcUcRN/KmIcx/nr63k6LYKL7sD0wH9okz6ltLPqOe1baOsvBwzJeAibR+Y8yCFffNL790g9bTXpnWB8VCOUdyDiaXi1g9ZYBfi/zeiytSDpsGElLL4emyf/amZh5i/QBn0glJ5GOmRbaaCHhrhs3ZrQZ7Xqc0wPBjcB0NTdycmlFweP+jeRWsgd5vqzICOrH+kxRJlhGW4v+r+pUeFtXyI=
before_install:
- git clone https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
- ln -sfT ${PWD}/target/travis-settings/settings.xml ${HOME}/.m2/settings.xml
- ln -sfT ${PWD}/target/travis-settings/mvnw mvnw
- ln -sft ${PWD} ${PWD}/target/travis-settings/.mvn
install: "${PWD}/target/travis-settings/java/install.sh -e -q -DexcludeGroupIds=uk.gov.justice.service,uk.gov.justice.services"
script: "${PWD}/target/travis-settings/java/script-install.sh coveralls:report sonar:sonar"
after_success: "${PWD}/target/travis-settings/java/after_success.sh"
notifications:
  slack:
    secure: fPlaMvrczZ2riJ4tjMOAqxSGj4JfxGlH/K08knLgG4T/n6EL4LN4+184Npz9XueNbV3m26WUrPkbXEiWXpqkKsbwcZXqqnFxGacGiyxv7LeBeQLYp7NFeARAyB5qDwUpjHlCPAEoAeyeGsZNrpui/wceY4j1tB7ObfdwbxLzAO0tekdbwitSaK1cc7V2sVHkBYr7ChuC+dVO1pshPw0EVTmzPioS8nfFKPaxWoMgyRAuYe7MD0U7DxNQ4Wzsb7tpfd5Oom1wLXyZ7M3wwSMMamIAAxHVG389Az6YvN7hXQggTGDawf/YwVOaoMR2bh7uHBCOiNZO1GbRTOA7IuTPwT7GsK94THRtfvqNm7RFBPkoD4657FATnk2o5c7QNTY3dAlYLsxLnS6mVTL/vAbqC7BbDHo/UGsxmOusQtKt8sRoL8pOCEInHaS3b88Osl7u7oYO/E4YTptdnkEe8tNyWWdx34nEUT0j1Mu/VAN38YcgTMUuiBU6chkMJ5BjIHisJlAAnBJ9VGgF9liqnigNwAGhbrHZPyAlKUX8HLejpD+t4aR0UaEvvauh6aHh4pYm0mZra4zOBC/lBDOXqsu5ajHL8LpHc6j+5FrmNwciiTVoxdud2S4c0U2ymr3L07ivX+UyhoraS9oSH3v7L73Q4NyvuAmD8Zc0xw/cR4Pff9c=
env:
  global:
  - PGPORT=5432
  - secure: UPI88KPr3E9kLMgbhEImAIDwOh05poEitez0zHx1540sDZsXPGgL4Q0WmfRm7QA0GmVY1aRSlu/AqF74Nr+jztIg9Py3wHtxrhLyg/G6gxu0gnFuecpZL+4mFyNRIVZUn53tR5ydcn8R30oPnQP+KHnRb5y12xPH9lfu6KB68FhlmLUqCKd9BAe/Q1FZNp21/smG9nWTpnU83yM1Oc9+8v1zCFbxU705FOSncpIlqHG10bi+6uWRg8STqmtNhTOj4Ymny7g3uDszQxdhjRRj30j6oOornhK2XgysdpDNdrnq0ez2A+gNhfzQn1uN258vhkkFONpb/3hfkjSbbZ1AG+iKtkCMp5n7kCiaraqO1rEqIwV7JQHJz/UKT7Az3glF/a2eYNRgAAXM9TJCz6xcjf6h5VnoMP/obusrjoA8hLzGYL8RXySvl2EH98adwRR9po36+itZuP7i8vW/HhzayCoSAjfbX7EgdUQClyvmSd5VELJpwGUpV+cQ1k1iEukpQb6eSiCCq/XXD7+IJRaSBV/dQVdWjVxz1EwAg8LfzYQiuRIPl15sKc+c8pA0/1juKyAArDV8CkKjaf9rCLdtEZtgWtAv6MgnnzDNrvZu2Hg901+32eR0jKEuHG4vybIU441YV/kScLSLlVQZjARQ3ZGiw7O4jT/Qlxxfs6qFuss=
  - secure: SWdo5DGTHhr0qUoDm+buUSNHYZq4yJsbgW8uPEilkY1O5Wer01f0QVVgggdhHrMaUeEQrsIIuLckaUW6SKLV4vBvjBEBk7AcGfz/AC98Hb0a8RXCxLKxR7xbXKMtggkmErUrBvhWqSbIQMmtf2823cdnUSl+ZZxm+gYtvJKQibjmNoVybfhMkXpGntBw+Zd5St3kitVbAJJMz4fKIcLpO0eZXDK6nTtMySjUlwve57IyFw0rvbV2YkHQijIXplpTtdyvVevAGCqLsahEhjAxJETakyYQP/XXT7dvm0QUemulWuQ1eugZJGGJRaE/x13f5yzg2MRFgVmEU3e4WY1V6KxS+PKo+RqHlW3TF/WqRiw7nLWjwo4UvO1a3jItokiDKQPzPYHYJbGg1jtpWiKHR2Tc41mXEiAr2z6IJAK/GfhkEW5YeXPvQmlIhVYg+WhewEXf1Xttv0xLyBIZlE54s6LtMKB+7HBTkdXso4ZeUClzBl5Q8MKlgaACDTs51PQpnHWV9leY8BBFnOtvoQU3YdXPoWR4s3O1WtT7BSF8n7E7Gj5ctXGZ6RHxGJJ/+WqoX5VDjYcc57+swbxsdd1YjYE8+83w/oKbGIgtnPDAvym4AcZnAnDrlQ5rWrJYHJkYk77o13NWNtMTRJNiMd+wmFMRsIbpQemmgx3GbbgN4Hg=
