dist: trusty
sudo: required
language: java
jdk:
- oraclejdk8
git:
  depth: 3
cache:
  directories:
  - "$HOME/.m2"
before_install:
- git clone https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
- ln -sfT ${PWD}/target/travis-settings/settings.xml ${HOME}/.m2/settings.xml
install: "${PWD}/target/travis-settings/java/install.sh -e -q -DexcludeGroupIds=uk.gov.justice.service,uk.gov.justice.services"
script: "${PWD}/target/travis-settings/java/script.sh coveralls:report"
after_success: "${PWD}/target/travis-settings/java/after_success.sh"
notifications:
  slack:
    secure: fPlaMvrczZ2riJ4tjMOAqxSGj4JfxGlH/K08knLgG4T/n6EL4LN4+184Npz9XueNbV3m26WUrPkbXEiWXpqkKsbwcZXqqnFxGacGiyxv7LeBeQLYp7NFeARAyB5qDwUpjHlCPAEoAeyeGsZNrpui/wceY4j1tB7ObfdwbxLzAO0tekdbwitSaK1cc7V2sVHkBYr7ChuC+dVO1pshPw0EVTmzPioS8nfFKPaxWoMgyRAuYe7MD0U7DxNQ4Wzsb7tpfd5Oom1wLXyZ7M3wwSMMamIAAxHVG389Az6YvN7hXQggTGDawf/YwVOaoMR2bh7uHBCOiNZO1GbRTOA7IuTPwT7GsK94THRtfvqNm7RFBPkoD4657FATnk2o5c7QNTY3dAlYLsxLnS6mVTL/vAbqC7BbDHo/UGsxmOusQtKt8sRoL8pOCEInHaS3b88Osl7u7oYO/E4YTptdnkEe8tNyWWdx34nEUT0j1Mu/VAN38YcgTMUuiBU6chkMJ5BjIHisJlAAnBJ9VGgF9liqnigNwAGhbrHZPyAlKUX8HLejpD+t4aR0UaEvvauh6aHh4pYm0mZra4zOBC/lBDOXqsu5ajHL8LpHc6j+5FrmNwciiTVoxdud2S4c0U2ymr3L07ivX+UyhoraS9oSH3v7L73Q4NyvuAmD8Zc0xw/cR4Pff9c=
env:
  global:
  - secure: xFRshq2P7UIwiMF+k99tyTg9MxdVshGA8nzRZz2LDOcHTeTebigHoYMHCLy8u7fGcFtiJwbrU+JsFZdJXBzXbxllyfyUC5p5xRkZuO8Dz21tLelmrzee1xq+cMM64fEwO5FGqFCLT9HGiPXBTJJCp59dNsc1OKO2Whkao4Sw3BpxIu+5K2A+op6wOV7gTsXjkLk3xrxFPSu8NGsFCCpGcFs94dLvVZBzlR8crgkHBV67puhQebRIAOFd6JXCkxRmDzquOxRokawvRZFmGWFoYI45vmY30Re7ddKWGkt8OvgSaPDQCwWS9wo2nK8Y6ketWfRkkN1veg6OZz5daPZCWsTUFxxC6G1q8inxNsUf5K1DrNAaFguEbutF/ETCUrQHeSDH1YrWcO96qxBXURqEDOVQnOZxYz1z2/RVa8VfLe7HP7e7OXG5QJulBRbRf6W77Jx0ZSkFU7Ep49G1sGLcDK7sTg7ICY37nVlB9Kp7/aWu24e2OdjIYLxN0Ol1jiXUWLzp8ROmk17fnJbG3c6ADNcPAHv75FcNrUUTp8hP6Wv0I18pnFqUiorIZcuiZo2GwsALMFYMFlNuVlt770yRBE9QJLIj7HynF49Ppc0Oa6koPl3P1nncdyVk5U9vL5NpVcK+S4cjm1xY7of64KeJvncCPTbL+9kMN1/FjQzk6h8=
  - secure: jYpqQP+l9giPz/6gtDwfc7+NFN0Dt0X18yTXqIsxU2Fq25tZ8htOfEACcrXlLuQKZE2W+C5vWrR+pNFcxCyNvncA/pMGoaLLWTqoLKmmit1jRe6DlMubbof8yCzwFSyrkkvyNFG0lB0d7gJNEKEvzsFC75Knl5/b/Kg1uMMKWgLQSHZPL1IQZTeas3CrEaRbAUiJaYbYSn5svPxLpS+ru/uifB4+EFpSvxdf3A13CXYSxlNas7kD/BG9BxUSIj3C3BeGfmARnO45gqofFREY813L12BDL4yHVsvAg6krA7lKxoYIyXYpLuVlPQg3XsaqJBEg2HfsYwvG9WH8EWYlrTIdpLWcU27VIIG1ezm5xB94xxVUQS2u3kxWKTDzJaNb3YzXuTe7kfb2pUjpbzSRBuhGzI5YjXZ7HXjqLbcCN+I0rh2keOii1ZW1LkUX3G2+V45dbDznUsVZORqMru/RiqAYVoFVFNxm+KD4e7qujCDBc1wJ9FaMmP48zWZSGom9J4zTD6/w7itZIDzu0Ld7tR0s2SS/lXcPHgZJsVZrcTZjAfCT1HamrzKTDecFgMCKw2FaiHkcHe3LfKEKAYohxN61BzMxMSYzml+/e6kKylqcGBULQQPAtnGkczAlgDsqVpg5QhZXLM2QCDf7pC9Zx54OFf77HC/22uQDOe9mQfY=
