dist: trusty
sudo: required
language: java
jdk:
- oraclejdk8
git:
  depth: 3
cache:
  directories:
  - "$HOME/.m2"
services:
- postgresql
before_script:
- psql -c 'create database frameworkeventstore;' -U postgres
- psql -c 'create database frameworkviewstore;' -U postgres
- psql -c 'create database frameworkfilestore;' -U postgres
- psql -c 'create database frameworksystem;' -U postgres
- psql -c 'create database fileservice;' -U postgres
- psql -c "CREATE USER framework WITH PASSWORD 'framework';" -U postgres
- psql -c "CREATE USER fileservice WITH PASSWORD 'fileservice';" -U postgres
addons:
  postgresql: '9.5'
  sonarcloud:
    organization: cjscommonplatform
    token:
      secure: FAGcFnJBPKyUQLCNA1ZjAQ0eLUZ+HQIDtJh10o9aML8bO+3GE8z8B+pIvAVYwepekXG1YfMvBT3+CmLiLVLO1G+oiI8Ov3tZnIUxWAjGmbyElcXp/FYlc/gemIx9yteZWd6Qi4KXpTARSJuFvSlHU1KoOduNSOPAzi1h4rVIEv27XlmKft3y/X5xWPFLTFnTMD8GP+NSF1JwiHzlbpiKFFgd2iIt5zufsQgdQOLiU3CdxGbKeejbUH7uau8X0xvVFTCa3cnv7YeWakSjSV2fO1WQMONRkr4zZ2vhI1GIREMfiiBhJYqAAs/mErJ7p6BVno2pIr4Si9Vml/xbPPuY6xWYzAd1KG/NdMzFgCNIwRW0MSPHaK5R9DrNqsagJqaa3TGGsFkOK9cQgaPz5BASPCryJG2oBHcwHyexLo5gR3KPLK5g+kedFn4F7olkeiDYtsDeVi1xtiGqUviG/PQR3VcUcRN/KmIcx/nr63k6LYKL7sD0wH9okz6ltLPqOe1baOsvBwzJeAibR+Y8yCFffNL790g9bTXpnWB8VCOUdyDiaXi1g9ZYBfi/zeiytSDpsGElLL4emyf/amZh5i/QBn0glJ5GOmRbaaCHhrhs3ZrQZ7Xqc0wPBjcB0NTdycmlFweP+jeRWsgd5vqzICOrH+kxRJlhGW4v+r+pUeFtXyI=
before_install:
- git clone https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
- ln -sfT ${PWD}/target/travis-settings/settings.xml ${HOME}/.m2/settings.xml
- ln -sfT ${PWD}/target/travis-settings/mvnw mvnw
- ln -sft ${PWD} ${PWD}/target/travis-settings/.mvn
install: "${PWD}/target/travis-settings/java/install.sh -e -q -DexcludeGroupIds=uk.gov.justice.service,uk.gov.justice.services"
script: "${PWD}/target/travis-settings/java/script-install.sh coveralls:report sonar:sonar"
after_success: "${PWD}/target/travis-settings/java/after_success.sh"
notifications:
  slack:
    secure: fPlaMvrczZ2riJ4tjMOAqxSGj4JfxGlH/K08knLgG4T/n6EL4LN4+184Npz9XueNbV3m26WUrPkbXEiWXpqkKsbwcZXqqnFxGacGiyxv7LeBeQLYp7NFeARAyB5qDwUpjHlCPAEoAeyeGsZNrpui/wceY4j1tB7ObfdwbxLzAO0tekdbwitSaK1cc7V2sVHkBYr7ChuC+dVO1pshPw0EVTmzPioS8nfFKPaxWoMgyRAuYe7MD0U7DxNQ4Wzsb7tpfd5Oom1wLXyZ7M3wwSMMamIAAxHVG389Az6YvN7hXQggTGDawf/YwVOaoMR2bh7uHBCOiNZO1GbRTOA7IuTPwT7GsK94THRtfvqNm7RFBPkoD4657FATnk2o5c7QNTY3dAlYLsxLnS6mVTL/vAbqC7BbDHo/UGsxmOusQtKt8sRoL8pOCEInHaS3b88Osl7u7oYO/E4YTptdnkEe8tNyWWdx34nEUT0j1Mu/VAN38YcgTMUuiBU6chkMJ5BjIHisJlAAnBJ9VGgF9liqnigNwAGhbrHZPyAlKUX8HLejpD+t4aR0UaEvvauh6aHh4pYm0mZra4zOBC/lBDOXqsu5ajHL8LpHc6j+5FrmNwciiTVoxdud2S4c0U2ymr3L07ivX+UyhoraS9oSH3v7L73Q4NyvuAmD8Zc0xw/cR4Pff9c=
env:
  global:
  - secure: Tzk6Mk+FXa4HWgPeUjc3o2y0PajgHomkffIocV4jsSWHfxwLba339jIwPTmQmvllna6y441qF1Cm6F90PfQHmxLicu8Z1TPiII++0/8XSUGWCEnTL80W7sIcu/ROOpQkrB5GG7H7c/cLenS6j9z3IDuV/geHkonuMjUkaMAh0Wo59Ab4AMs/nbMpp71lq5XrahxDLPxmhegujwRXuCmdHfehVRjZemkHASddQ4ZNS7liQwnIeZvPu093NuxWH9SblJ6Hlt4KigUZkJjiH8iJTAXBLQ6UhwKxwXo7G8ERDPw5qRk35X8GCx9cCesr2nGwozS0e1pYPMeXHO2ckgunIcsdwnSe8hOBqgCk/TpoB3srD/5x0TxgtyiD+kSIKz1+kZAVXl5e+oc8AmjtAMUQA1BFC4wN2/z6UUXsGHy6Sa/ZEWA+OslZiQZu426/ZmX3298kFaWWSwt9isd2uK8txZSHIDTRzZbvLyIUepe7PXOWXh6EyscsEPtksdkb2VW/W0r2hsYOSTDVtaQuozyIeUaIAXq93lhUKoITvGvmxeSEnVLIlM6h0GyeL4jqzn8yUaoJ/clzeLOZAT25xAjKSYpx3MXnuroeDVXUra+Y3542vC0zuBLgeJxwR8gBKnGO0GJhloIipkxGWbWzF2EQcmp67YQkiOwv+ApA3XvTU1c=
  - secure: iEjZCoKb3CHqyhDQ7Ap3iRlhPpRh6VrVPqInIS8KLK/JPJa7csal0qVwqjwvsgnnz45E0pvpy7MtE2YKsnDxzDRiMNQb7FT1EVpM26fuTUprWkxXx7HoALFj7iDdk554UGMgw+HYFmDKYPteNtjbAj8QFlr5fI+SFSPzgDqvUSovIiKfLOZTKl645e58Uf54pzk+g9w7SJjMDQe4q6ySzAV/EOvWpUGugdaiBgdGJw0x32EG2osdYB+5H0CoG4TfYv2BF7ctbrJsxsPeRS9VKAmaQlC4L0HVzjO5PSYf4f6pND265UVrRxzU5uBOkG96dhIJjqbpfUo0lOc+3rFNxMehodVhCSKj2DzVZ4dA5F4PZJ368TLxhcFQFn031Rk1Ct/s27lBB9KOzq38bAbET30p+zUGXBLgZnBaxypiIbevAU6n0IIpDnFrV8myRV/TtJ2nEADr3w5LjUTLhAMPx2C5Wx/wb6u+k1CcTPRSUMBsPlpQNhTU1TwU6Y1DpTQIzRjkF1RCmmo6VtLouj+KOGw7OOxQFGsZ5HfkC8GdAqehVMg+08Yyqg0gN9rzgiVinw1MtCxMpEAatM4RYyLTonQRIXI1+h6QwlIRlQrSg8pqtm/5Itfl7bdIzL+WwML4SRW/47seoUeTTs3ff4Jg1wSbT+StqYsviKKPhrchPic=
  - PGPORT=5432
