dist: trusty
sudo: required
language: java
jdk:
- oraclejdk8
git:
  depth: 3
cache:
  directories:
  - "$HOME/.m2"
services:
- postgresql
before_script:
- psql -c 'create database frameworkeventstore;' -U postgres
- psql -c 'create database frameworkviewstore;' -U postgres
- psql -c 'create database frameworkfilestore;' -U postgres
- psql -c 'create database frameworksystem;' -U postgres
- psql -c 'create database fileservice;' -U postgres
- psql -c "CREATE USER framework WITH PASSWORD 'framework';" -U postgres
- psql -c "CREATE USER fileservice WITH PASSWORD 'fileservice';" -U postgres
addons:
  postgresql: '9.5'
  sonarcloud:
    organization: cjscommonplatform
    token:
      secure: FAGcFnJBPKyUQLCNA1ZjAQ0eLUZ+HQIDtJh10o9aML8bO+3GE8z8B+pIvAVYwepekXG1YfMvBT3+CmLiLVLO1G+oiI8Ov3tZnIUxWAjGmbyElcXp/FYlc/gemIx9yteZWd6Qi4KXpTARSJuFvSlHU1KoOduNSOPAzi1h4rVIEv27XlmKft3y/X5xWPFLTFnTMD8GP+NSF1JwiHzlbpiKFFgd2iIt5zufsQgdQOLiU3CdxGbKeejbUH7uau8X0xvVFTCa3cnv7YeWakSjSV2fO1WQMONRkr4zZ2vhI1GIREMfiiBhJYqAAs/mErJ7p6BVno2pIr4Si9Vml/xbPPuY6xWYzAd1KG/NdMzFgCNIwRW0MSPHaK5R9DrNqsagJqaa3TGGsFkOK9cQgaPz5BASPCryJG2oBHcwHyexLo5gR3KPLK5g+kedFn4F7olkeiDYtsDeVi1xtiGqUviG/PQR3VcUcRN/KmIcx/nr63k6LYKL7sD0wH9okz6ltLPqOe1baOsvBwzJeAibR+Y8yCFffNL790g9bTXpnWB8VCOUdyDiaXi1g9ZYBfi/zeiytSDpsGElLL4emyf/amZh5i/QBn0glJ5GOmRbaaCHhrhs3ZrQZ7Xqc0wPBjcB0NTdycmlFweP+jeRWsgd5vqzICOrH+kxRJlhGW4v+r+pUeFtXyI=
before_install:
- git clone https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
- ln -sfT ${PWD}/target/travis-settings/settings.xml ${HOME}/.m2/settings.xml
- ln -sfT ${PWD}/target/travis-settings/mvnw mvnw
- ln -sft ${PWD} ${PWD}/target/travis-settings/.mvn
install: "${PWD}/target/travis-settings/java/install.sh -e -q -DexcludeGroupIds=uk.gov.justice.service,uk.gov.justice.services"
script: "${PWD}/target/travis-settings/java/script-install.sh coveralls:report sonar:sonar"
after_success: "${PWD}/target/travis-settings/java/after_success.sh"
notifications:
  slack:
    secure: fPlaMvrczZ2riJ4tjMOAqxSGj4JfxGlH/K08knLgG4T/n6EL4LN4+184Npz9XueNbV3m26WUrPkbXEiWXpqkKsbwcZXqqnFxGacGiyxv7LeBeQLYp7NFeARAyB5qDwUpjHlCPAEoAeyeGsZNrpui/wceY4j1tB7ObfdwbxLzAO0tekdbwitSaK1cc7V2sVHkBYr7ChuC+dVO1pshPw0EVTmzPioS8nfFKPaxWoMgyRAuYe7MD0U7DxNQ4Wzsb7tpfd5Oom1wLXyZ7M3wwSMMamIAAxHVG389Az6YvN7hXQggTGDawf/YwVOaoMR2bh7uHBCOiNZO1GbRTOA7IuTPwT7GsK94THRtfvqNm7RFBPkoD4657FATnk2o5c7QNTY3dAlYLsxLnS6mVTL/vAbqC7BbDHo/UGsxmOusQtKt8sRoL8pOCEInHaS3b88Osl7u7oYO/E4YTptdnkEe8tNyWWdx34nEUT0j1Mu/VAN38YcgTMUuiBU6chkMJ5BjIHisJlAAnBJ9VGgF9liqnigNwAGhbrHZPyAlKUX8HLejpD+t4aR0UaEvvauh6aHh4pYm0mZra4zOBC/lBDOXqsu5ajHL8LpHc6j+5FrmNwciiTVoxdud2S4c0U2ymr3L07ivX+UyhoraS9oSH3v7L73Q4NyvuAmD8Zc0xw/cR4Pff9c=
env:
  global:
  - PGPORT=5432
  - secure: JGPDmzYX1Q6qnQYr3eC9Ez6RhXzaGh5LFwvuxpY3cUkeMSbl76WlefpgGZ1BJ/PFJQz6JixinqxQDSb7HYN6X67jJvc/P6HQFPBZJRZFo/Y2sQO9Oj6KBIdbRmxMV4HVH6eoV3PI3xkPzjpc6aH094vDRQmVMI+gUE6doDhY8NgRWJvNWtQS3AiMG7ZFKCoTS8EcPYmVqisS3F9cnryUWudLp7VBKxIa3Bsaa9bquOhADDm8UU1F8zL2KCaAfGUcH6xoVFMrNyGjwTdS27ai5c+Vx/08VbpufkSJyfwBkPFNlcT5t/lHR39zk1BapA/0OeA2Nhh4y4WplQsktdJB7PvS+AX+2aZtdZphE1rbve/7RqfSGUeWnM5p6tvmB3f50rG9I5LjprEQyJ03t3g3wc2ZXPsqGAbIUwwZ07SYZnkwyG8lIAE5Jwv281qY9c5+xSSqOMOrqoQykeWKjCnU/C5A2fYsENKRhhEU23pcNWL913gqc5a3VYjB42Jr/chBxLgyABorNhHaPhagyKs7gXD798rrwRiit+h8m/22HA7pQ80wuPGuEB7ruW7HNazZqRa8m7KjlR8EUb52urBMC/S+BxfNMpHPuJ3cCQy4+JbMKZApPbHC6Bj0Es1Jz3poDstYqZiTuPvz8zGIDPJjIAoO/gwTXlr6B/eQ0NfTr+A=
  - secure: P/IvzVAanDtSA328FL8OVZydTxoFqGYaqrbC4AjtUCQUv3KkRVvd59Z2ClFpfxFBzex0VvHPp7qtdEYIXOqjR+1FOX46XHNhWCs83fZBvh35XJ7Y2f0jW/xqq6hnnp8a79QkeVR133N7HHzI161XZbtIQT00Oo57q1/5iZXPceSbJW7uLZTTxP8MZVuPG9bz0ki0CygF3viz3HflIpz42GRaaGdKgCCYvVYfCKoL2cJMJJMuus5lrOqa59N23tQFc0ifdYtU59cQXUD4jPDJA0zrlbebb3hUcsHXqCLDNKVeGL70jFL0xt2h4Wen3XQ2dDX5t/9uSlXnuAPwsOPKck+eTD1zedmWqGY+JesNmFyncKCcP6E94RiL1vXrNaDV911AQMMYGO8iKpLwFaKIpqmEcOAw6+29F7ewod/bKm3zbsA59UZfy+21Tsix0LwwGM+B4JBIVWuQBwnso3o2UCozVwbC5tDvQxxDpcmkux/ZngFjcMIVud+/Rdx4/5qLyCFO7J0Ei77FHWm/7BZeOcRjlth/pLn4RUE7D1ly7vQN7iLWu+OGIxp3KosT1jUBP9glxRm9fpydRefUy7egO07d/Sf+98HBB+ACrcOl2tbSJv9GxDrUR6EJUGVa4UtP2vtfOPJ8hfXGq3h41ZssAum8m4nFZtETNvFTvUIYoyA=
