dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
git:
  depth: 3
cache:
  directories:
  - "$HOME/.m2"
addons:
  sonarcloud:
    organization: cjscommonplatform
    token:
      secure: vSbeXDyjUHHT0X0Nc2m860oYRTYnKyocAKwlE/1mQAf7+1OxDNPCkjkjzDPK8s8TdwrE4m2kAQHjXS40TwWAKBovv7RdZRAYC6nJHdUt5RZLV62QZzhXqdOnpMMtXcixYRAR1tU61b1nMB/u+6cujGSEdaHQPu1hhKEbiedfAX2h4GnAFBMxNKe+3aG0xmdPmF/2cAqVTj5HvOybyhlU368Nlbk3/OLWBzFaTUHchikLtE01L2T0Goj4gOYSOib7b7iwBhbuL0+O7DMInlyGBLhGG4feJN1SC2JNFGyaKLOF2tEbiVviGRnt8pEnnkKwDTNZwBmc2yQHr8jYkiY0xF7yZiDQTocGxxpDX2alFUDBnysHLa92YU6CYUC3vxHC2mx9VACHhst+skckYk2rTkWm6cBPZbnq2ZiJOf1tqMyaMothocIVnaPjpmuf4Ujwmsz4fZDzriBMIKJdN0boA0IW/bYgieXoOlUrU99HHzcnTdr/VE1k7KyUQxUxBGnkfbipMQNcWbRh/bpUuco7hqknBEE5fMFMYYW8yfeyvTjkIDFTYNWLf9CJjKpQ5gonbCB7BDJT3PObVO0I6Haq33pv/1Ihdg9Rvh6KY4EuniPQbyef631eRF7zDSlqH0BtZI5NTPKzaY95xPHlOvJnNKWuLo/OjJhmPOAmX/myLag=
before_install:
- git clone https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
- ln -sfT ${PWD}/target/travis-settings/settings.xml ${HOME}/.m2/settings.xml
install: "${PWD}/target/travis-settings/java/install.sh -DexcludeGroupIds=uk.gov.justice.utils"
script: "${PWD}/target/travis-settings/java/script-install.sh coveralls:report sonar:sonar"
after_success: "${PWD}/target/travis-settings/java/after_success.sh"
env:
  global:
  - secure: dCrAn1W0rqVW3qoedURgjfY6cZt5aelXV0ps4S4+AisGsMZ5vr5DXvN87Ui2CASUNfiESRkEFfMgQhwom5kJkH+/FS5zX4psAmuvpyMto5WBoWtqZO7c+jUzL0DB4thwOYtVP+xn8WNlNBg5wlJ2z4M8zAMCgx7G5nPudFtvP0o/xJ+jvtuqPWvEBE9P+Z/UQaX6xp3Y4zoyKM3NgFrWaJv0xdN8hnJZymh9/Wjnp05IyXG+Bu2CO6PppPlHKo/KA/XboRKdlJ42MXGRWfe+4kJOYGP9EVQqVNHeqHFJB7dSoy/Z7k3H5rNlZVwCe7W3TTbUJoz06aC+znYc1oPt209OO2t6kiopm6SSg1lvsZetJwneapWTryRGhJTQS0WUgpZ1jv91UE66A+r/jQasMHSqW5/SvcIe41RIo7gLx1So88F9r8dfPHzVOM/+3VP36BaarzZ/kPoUVGyZ0KsUlA9/9CTVhrzBUm9P5J+xOFMw2/KMSF0XdVXqFqI/fZxyVYTcJBbHDhfirOQ7u2kylTzM/403DgZ/jBQiFd4yZ/6f0Ws4eVUYJc8pc4PEmo7uhtXmw/hGGXfhOWiLZ7SUtJ1aL09XfiBlp27vojococawg01dywHK9lp+fRNFzKcLu/G/fvtJCWqytoeWMXwbTf/UyEzyEvOGG6nrpDnt32w=
  - secure: W2SfaDoZS89QhkwOpvK/fGfhz6i/lxdrN/GgnvGEjp49nQuOjgzkHqmnGx0iU88A2Ej4m+aO6hWeUAF1JkL6pNM/w0K13GPoYCztSRdj4iav9+qzYL4i9shMhH35F3Ov2OcNqlZUvpg8/IyMKci/skg876BjuQcvhnu5LphcbZZOGNos/aLnBk4RPPAEr3vjSjAS/wxuo+7SX6qA8HHRiLbOxfxmCx6RZO2iMeIOAuHcPp3Qi8qViF5cR1DiLBoddrkp3AQr5GkNH57mkSZdJifC4TD1vgtrOOjnsD3en3IKV55MFUTkrPExrMnob+zqqQD9VeLyU5zkp8XTTzud+euVkxbsLN+KqNl2ANJ2J6n3Ijl8mtm+mhydDuqxuq2MxL0oCcjB2Ddk3QMlDfjPn89setvxpjnhfb1+sg4kPB0HIaVmVa59jAFtbg48uw6bOV1msqExqtyi/FcE25cCZIrV/8MGc7jn6Cy9jcNXyw1tS2YPIoqZU5daCFbHZPNoadlGdeBgSKnDUoUQygvfG7KxXvqpxsosPRswa4HPLoyIE1DDaCkEezLe25r+Nm6nVItaZTfpxWoyiYbcjDA/9j2sfTc7ZH7WUlKgT5MifFy5+ZxKkBZ5fMMPLHyJFKggFMEdDPN9GDnYoTjkuSTK3hM3KJcz1SCKY+Oym2N/dyM=
